/**
 * Large supplemental static pools — merged with core fallbacks when the API is
 * unavailable or fails. AI path remains primary when OPENAI_API_KEY is set.
 */

export const EXTRA_TRUTHS_PG: string[] = [
  "What's a text habit you have that says more about you than you think?",
  "When do you go from curious to invested — what's the tipping point?",
  "What's something you judge silently on a first date?",
  "What kind of listener makes you open up faster?",
  "What's your honest relationship with 'the ick'?",
  "What would make you un-match faster than anything else?",
  "What's a small thing that builds trust for you in chat?",
  "What's your pattern: over-text or under-text when you're into someone?",
  "What do you need to know before you'd meet in person?",
  "What's a compliment that felt cheap vs one that felt earned?",
  "When did you last change your mind about someone after one good conversation?",
  "What's your 'I'm actually listening' tell?",
  "What would you rather know early: intentions or chemistry?",
  "What's something you're working on in how you date?",
  "What's a myth about dating you don't buy anymore?",
  "What makes you feel safe enough to be playful?",
  "What's your favorite way to show interest without saying it outright?",
  "What would your close friends say is your blind spot in dating?",
  "What's a non-physical trait you fall for repeatedly?",
  "When do you know it's time to stop texting and meet or walk away?",
];

export const EXTRA_TRUTHS_R: string[] = [
  "What's the hottest message you've ever received that was still classy?",
  "Have you ever used someone for attention while telling yourself you weren't?",
  "What's your line between chemistry and chaos?",
  "What's something you've only done behind a locked phone screen?",
  "When did you last want someone you knew you shouldn't?",
  "What's a turn-on that's mostly about how they think?",
  "Have you ever faked indifference to win — did it work?",
  "What's the adult version of 'playing hard to get' for you?",
  "What's a fantasy that's more about control than romance?",
  "When did you last send something you almost unsent?",
  "What's your honest take on friends-with-benefits working long-term?",
  "Have you ever caught yourself mirroring someone's attachment style?",
  "What's something you'd try once with the right person?",
  "What's the meanest thing you've thought about an ex that you won't say out loud?",
  "What's a boundary you set that actually improved your dating life?",
  "When does jealousy feel hot vs toxic to you?",
  "What's a lie you tell on dates to seem cooler?",
  "What's the fastest you've gone from strangers to something real?",
  "Have you ever stayed for the tension when you should have left?",
  "What's your weakness when someone is good with words?",
];

export const EXTRA_TRUTHS_SPICY: string[] = [
  "What's the most shameless thing you've done to keep someone's attention?",
  "What would you admit only after the third drink — or the third date?",
  "What's something you'd let slide if the chemistry was unfairly good?",
  "Describe the kind of message that would make you change your evening plans.",
  "What's a risk you'd take in person that you'd never admit in your profile?",
  "Have you ever wanted someone more after they pushed back a little?",
  "What's your honest 'type' when the lights are low and the filter is off?",
  "When did you last feel genuinely desired — not just wanted?",
  "What's a line you won't cross in chat even when you're tempted?",
  "What's something about your drive or appetite you'd only share with a match?",
  "Have you ever negotiated your own boundaries because the pull was strong?",
  "What's the most adult game of chicken you've played with attraction?",
  "What would make you reply to a risky text instead of leaving them on read?",
  "What's a scenario you've replayed in your head more than twice?",
  "When does 'too much' become just enough for you?",
  "What's something you'd want a green light on before you escalate?",
  "Have you ever regretted holding back when you should have gone for it?",
];

export const EXTRA_DARES_PG: string[] = [
  "Voice note: one thing that would make you say yes to a second chat",
  "Send a selfie: the face you make when a message is *good* good",
  "Reply with one sentence that sounds like the start of a novel about tonight",
  "Send a 5-sec video: shrug that means 'maybe' or 'try me'",
  "Voice note: compliment them on something only someone paying attention would notice",
  "Text a question you'd ask if you were already on a date",
  "Send a selfie holding something random — caption ties it to your vibe",
  "Voice note: your honest first impression of their energy — kind version",
  "Reply with two truths, no lie — about what you want from dating right now",
  "Send a 4-sec video: slow nod like you're impressed and intrigued",
  "Voice note: one thing you're picky about that you won't apologize for",
  "Text the emoji that best matches your dating philosophy",
  "Send a selfie: 'I'm listening' face, no words",
  "Voice note: one thing you'd want them to know before you ever meet",
  "Reply with a one-line roast of your own dating history — gentle",
];

export const EXTRA_DARES_R: string[] = [
  "Voice note: describe the vibe you'd want if you showed up to meet them",
  "Send a selfie: 'I know what I'm doing' energy — still PG",
  "Text three escalating compliments — each one bolder than the last",
  "Voice note: one thing about their vibe that messes with your focus",
  "Send a 6-sec video: lip corner twitch like you're holding back a thought",
  "Reply with what you'd text if you were testing whether they're bold too",
  "Voice note: admit a double standard you have in attraction — funny but true",
  "Send a selfie from the collar up — intentional, not accidental",
  "Text a dare back: one thing you want to see from them next",
  "Voice note: the kind of tension you like before a first kiss — no play-by-play",
  "Send a 5-sec video: look away then back like you decided something",
  "Reply with a line that's flirty enough to raise eyebrows, safe enough for chat",
  "Voice note: one 'rule' you'd break if they asked the right way",
  "Send a selfie that says 'don't start something you can't finish' — joking tone",
  "Voice note: what 'good trouble' means in flirting, for you",
];

export const EXTRA_DARES_SPICY: string[] = [
  "Voice note: the boldest thing you'd whisper if the room were empty — still respectful",
  "Text a line that would get you blocked on a lesser app but is perfect here",
  "Voice note: one thing you'd want permission before you'd say out loud",
  "Send a selfie: shadow on jaw or cheekbone — moody, not explicit",
  "Text what you'd type if you were one drink braver — still respectful",
  "Voice note: describe your type using only verbs, no nouns for body parts",
  "Send a 5-sec video: exhale like you just decided to stop playing safe",
  "Reply with the compliment you'd give if you weren't worried about intensity",
  "Voice note: one boundary that's negotiable vs one that isn't — one sentence each",
  "Send a selfie: eyes + half a smile — let them fill in the rest",
  "Text a hypothetical 'if you were here…' that stops before it goes explicit",
  "Voice note: admit what kind of message would make you reset your whole night",
  "Send a 6-sec video: adjust your shirt collar once — slow, deliberate",
  "Reply with two words you'd want carved into a match's brain — spicy but not crude",
  "Voice note: what 'almost' feels like to you — almost kiss, almost text, almost rule broken",
  "Send a selfie in warm light that feels private without showing skin",
  "Voice note: one thing you'd want them to say before you'd lean in first",
];
